# Generated by Django 3.2.3 on 2021-05-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='Ingredients', to='main.Ingredient'),
        ),
    ]
