# Generated by Django 3.2.3 on 2021-05-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
