# Generated by Django 3.2.3 on 2021-06-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210601_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
